### ISSUE TITLE
Local Runtime - Up task get error

### ISSUE THREAD

**Issue by justgod3** [eclipse-velocitas/vehicle-app-python-template#163]
![image](https://github.com/eclipse-velocitas/vehicle-app-python-template/assets/41788824/ad520e04-f7b1-40d3-b57f-3cf0141cebc7)
get the error:

 正在执行任务: velocitas exec runtime-local up 

Hint: Log files can be found in your workspace's logs directory
> mqtt-broker running
Traceback (most recent call last):
  File "/home/vscode/.velocitas/packages/devenv-runtimes/v1.0.1/./runtime-local/src/runtime-up.py", line 81, in <module>
    run_services()
  File "/home/vscode/.velocitas/packages/devenv-runtimes/v1.0.1/./runtime-local/src/runtime-up.py", line 38, in run_services
    spawned_processes[service_id] = run_service(service)
  File "/home/vscode/.velocitas/packages/devenv-runtimes/v1.0.1/runtime-local/src/lib.py", line 136, in run_service
    env_vars[pair[0].strip()] = replace_variables(
  File "/home/vscode/.velocitas/packages/devenv-runtimes/v1.0.1/velocitas_lib/velocitas_lib.py", line 86, in replace_variables
    raise KeyError(f"{input_str_value!r} not in {variables!r}")
KeyError: "'builtin.cache.vspec_file_path' not in {'builtin.package_dir': PosixPath('/home/vscode/.velocitas/packages/devenv-runtimes/v1.0.1')}"
Program returned exit code: 1

**Comment by MP91** [comment]
Hey @justgod3,

could you provide some details about your setup? 
What exactly have you done before?
Did you change the VehicleModel in the AppManifest?

**Comment by justgod3** [comment]
@MP91 ,sorry, When I delete the old project and re-pull the newest project,it is fine. thank you
